version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dwitter
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis
    volumes:
      - ./redisdata:/data
    ports:
      - '6374:6379'
    entrypoint: redis-server --appendonly yes
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
    ports:
      - "4500:4500"
    environment:
      - DEV_DATABASE_URL=postgres://postgres:postgres@db:5432/dwitter
      - PORT=4500
      - NODE_ENV=development
      - REDIS_HOST=cache
    volumes:
      - .:/app
    command: npm run dev