version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dwitter
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis
    container_name: cache
    volumes:
      - redis-data:/data
    ports:
      - '6374:6379'
    entrypoint: redis-server --appendonly yes
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always
    ports:
    - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - kafka-data:/var/lib/kafka/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./synonym.txt:/usr/share/elasticsearch/config/analysis/synonym.txt
      # - ./elasticsearch-config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - node.name=elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elastic
    volumes: 
      - kib-data:/usr/share/kibana/data
      # - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
      - kafka
      - elastic
    ports:
      - "4500:4500"
    environment:
      - DEV_DATABASE_URL=postgres://postgres:postgres@db:5432/dwitter
      - PORT=4500
      - NODE_ENV=development
      - REDIS_HOST=cache
    volumes:
      - .:/app
    command: npm run dev
  consumer:
    container_name: consumer
    build:
      context: ./services/kf-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - elastic
      - server
      - cache
    ports:
      - "4501:4500"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=cache
    volumes:
      - ./services/kf-consumer:/app
    command: npm run dev


volumes:
  es-data:
  kib-data:
  pg-data:
  redis-data:
  kafka-data:
